disabled_rules:
  - identifier_name
  - nesting
  - cyclomatic_complexity
  - todo

opt_in_rules:
  - implicit_return
  - explicit_init
  - redundant_nil_coalescing
  - fatal_error_message

included:
  - Sources
  - SpaceCadetApp
excluded:
  - .build
  - build
  - DerivedData
  - SpaceCadetApp/SpaceCadetApp.xcodeproj

line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true

trailing_whitespace:
  ignores_empty_lines: true

analyzer_rules:
  - explicit_self
